// Database types - auto-generated by Supabase
// To regenerate: npm run gen-types
// Note: You need to set SUPABASE_PROJECT_ID environment variable

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      regions: {
        Row: {
          id: number
          name: string
          level: string
          parent_id: number | null
          created_at: string
          updated_at: string
          // Add more fields as they exist in your database
        }
        Insert: {
          id?: number
          name: string
          level: string
          parent_id?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          name?: string
          level?: string
          parent_id?: number | null
          created_at?: string
          updated_at?: string
        }
      }
      // Add other tables as they exist in your database
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

// Type helpers
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type Inserts<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type Updates<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']